style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/IgnisDa/ryot
options:
  commits:
    filters:
      Type:
        - feat
        - build
        - fix
        - perf
        - refactor
        - ci
        - docs
  commit_groups:
    title_maps:
      feat: Features
      build: Build
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      ci: CI
      docs: Documentation
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
